version: 2
sources:
  - name: raw
    description: "Raw data layer - original Excel data loaded by Python script"
    schema: raw
    tables:
      - name: raw_loans
        description: "Original loan data from Excel file"
        columns:
          - name: "Loan ID"
            description: "Unique loan identifier"
          - name: "Customer ID"
            description: "Unique customer identifier"
          - name: "Current Loan Amount"
            description: "Current loan amount"
          - name: "Credit Score"
            description: "Customer credit score"
          - name: "Term"
            description: "Loan term (short/long term)"
          - name: "Purpose"
            description: "Loan purpose"
          - name: "Home Ownership"
            description: "Home ownership status"
          - name: "Years in current job"
            description: "Years in current job"
          - name: "Loan Status"
            description: "Loan status"
          - name: "Annual Income"
            description: "Customer annual income"
          - name: "Monthly Debt"
            description: "Customer monthly debt"
          - name: "Years of Credit History"
            description: "Years of credit history"
          - name: "Months since last delinquent"
            description: "Months since last delinquency"
          - name: "Number of Open Accounts"
            description: "Number of open accounts"
          - name: "Number of Credit Problems"
            description: "Number of credit problems"
          - name: "Current Credit Balance"
            description: "Current credit balance"
          - name: "Maximum Open Credit"
            description: "Maximum open credit"
          - name: "Bankruptcies"
            description: "Number of bankruptcies"
          - name: "Tax Liens"
            description: "Number of tax liens"
